driver:
  name: terraform
  version: "0.12.6"
  variable_files:
    - terraform.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      attrs_outputs:
        dns: server_name     
      controls:
      - check_rails_site
      user: ubuntu
      hosts_output: server_name
      key_files:
      - /home/gberchev/Dropbox/ec2_key_pair/us-east-1-key-pair.pem
       
suites:
- name: default
